language: r
cache: packages
dist: trusty
sudo: false
warnings_are_errors: true
bioc_required: true
before_install:
- Rscript -e 'update.packages(ask = FALSE)'
env:
  global:
    secure: ttQCjUTr5a6yuD7biyhtHa4PComjz4s3kjfRftUKgsIDgmOxfXUQHg6oHZphV3YgR7A5TPgeuD5ONlDTDBkEUlwk+1dUp/eedS21LplfekoxjLKn6e1gL2V86CzuA/k7JdJVVlWtnrNgMvEjo59DDwUHRQL626fzFhbNR7Jk1RffjXAXRJBj+r2bKfujSmSDzXTa8cuuAX5ZPmQsh6GbKpEaZ8/bpu6u6incH0tGrJkM9dVmOHrNzwEcWj/IJ9TDDQe8XxKW8/TldEk4ejymwHjI3LI4HpZU9V6c7TU5m7t4noI5qVz3IEfxTF5WR9WtNpCsJXgtJc+Wv/InrzA4oAbZ0p7XYt7QxGWOXnEghRRs3PnnKKZff1FqIeFWv+ZL2KVdwEtEb2+9iFgFkipRNr7pS+K0yJnRttZhPzjIjNrrGgcXHahpvMXy/f2tP77BtY6CbASfog48O5IJRN5etfgdK5M83ERd0xeCCMz6ZSVVQqiYSfzRWtBksvot0AbF+uW66F8sQV9vw5KwGfUI1sYmC10B+nAGK2Uf0MKFjIoorPXYEWELP2gSfrKdHgaA9hK7xyhGyjF+vGSuOzx6ZtMt61dR9QlxS1nihG2D5e0bzNWwJMupCbBYZX4GMaGgQlEG+x9fV6//k1aFSJNCKHgg0+nzFiWOrN7TEY9RY6U=
